// whosee-nextjs/src/components/ui/search-box.tsx
'use client';

import { Search, X } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useState } from 'react';
import { cn, isValidDomain, sanitizeDomain } from '@/lib/utils';

interface SearchBoxProps {
  onSearch: (domain: string) => void;
  loading?: boolean;
  className?: string;
}

export function SearchBox({ onSearch, loading = false, className }: SearchBoxProps) {
  const [domain, setDomain] = useState('');
  const [error, setError] = useState('');
  const t = useTranslations('home');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!domain.trim()) {
      setError('Please enter a domain name');
      return;
    }

    const sanitized = sanitizeDomain(domain.trim());
    
    if (!isValidDomain(sanitized)) {
      setError('Please enter a valid domain name');
      return;
    }

    setError('');
    onSearch(sanitized);
  };

  const handleClear = () => {
    setDomain('');
    setError('');
  };

  return (
    <div className={cn('w-full max-w-2xl mx-auto', className)}>
      <form onSubmit={handleSubmit} className="relative">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 dark:text-gray-400 h-4 w-4" />
          <input
            type="text"
            value={domain}
            onChange={(e) => setDomain(e.target.value)}
            placeholder={t('placeholder')}
            className={cn(
              'w-full pl-10 pr-20 py-4 text-lg rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800',
              'focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent',
              'placeholder:text-gray-500 dark:placeholder:text-gray-400',
              error && 'border-red-500 focus:ring-red-500'
            )}
            disabled={loading}
          />
          {domain && (
            <button
              type="button"
              onClick={handleClear}
              className="absolute right-16 top-1/2 transform -translate-y-1/2 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100"
              disabled={loading}
            >
              <X className="h-4 w-4" />
            </button>
          )}
          <button
            type="submit"
            disabled={loading || !domain.trim()}
            className={cn(
              'absolute right-2 top-1/2 transform -translate-y-1/2',
              'px-4 py-2 bg-blue-600 text-white rounded-lg',
              'hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500',
              'disabled:opacity-50 disabled:cursor-not-allowed',
              'transition-colors'
            )}
          >
            {loading ? (
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
            ) : (
              t('search')
            )}
          </button>
        </div>
      </form>
      
      {error && (
        <p className="mt-2 text-sm text-red-500">{error}</p>
      )}
    </div>
  );
}

// src/lib/components/SearchBox.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fly } from 'svelte/transition';
  import { createEventDispatcher } from 'svelte';
  
  const dispatch = createEventDispatcher();
  
  let query = '';
  let searchHistory: string[] = [];
  
  onMount(() => {
    const storedHistory = localStorage.getItem('searchHistory');
    if (storedHistory) {
      searchHistory = JSON.parse(storedHistory);
    }
  });
  
  function handleSearch() {
    if (!query.trim()) return;
    
    // 添加到搜索历史
    if (!searchHistory.includes(query)) {
      searchHistory = [query, ...searchHistory].slice(0, 5);
      localStorage.setItem('searchHistory', JSON.stringify(searchHistory));
    }
    
    dispatch('search', { query });
  }
  
  function clearInput() {
    query = '';
  }
</script>

<div class="search-container">
  <div class="search-box">
    <span class="search-icon">🔍</span>
    
    <input
      bind:value={query}
      type="text"
      placeholder="请输入要查询的域名..."
      on:keydown={(e) => e.key === 'Enter' && handleSearch()}
      class="w-full px-4 py-3 pl-12 text-lg bg-gray-100 rounded-full border border-gray-300 text-gray-800 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-400"
    />
    
    {#if query}
      <button 
        class="clear-btn absolute right-16 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
        on:click={clearInput}
      >
        ✕
      </button>
    {/if}
    
    <button 
      class="search-btn absolute right-4 top-1/2 -translate-y-1/2 px-4 py-2 bg-gray-500 hover:bg-gray-600 rounded-full text-white transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      disabled={!query.trim()} 
      on:click={handleSearch}
    >
      搜索
    </button>
  </div>
  
  {#if searchHistory.length > 0}
    <div 
      class="search-history mt-4 text-gray-600"
      transition:fly={{ y: 10, duration: 200 }}
    >
      <span class="history-label text-sm">历史记录:</span>
      
      <div class="history-items flex gap-2 mt-2 flex-wrap">
        {#each searchHistory as item}
          <button 
            class="history-item px-3 py-1 text-sm bg-gray-200 hover:bg-gray-300 rounded-full transition-colors text-gray-700"
            on:click={() => { query = item; handleSearch(); }}
          >
            {item}
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>

<style>
  .search-container {
    @apply w-full max-w-2xl mx-auto;
  }
  
  .search-box {
    @apply relative;
  }
  
  .search-icon {
    @apply absolute left-4 top-1/2 -translate-y-1/2 text-gray-500;
  }
</style>
